### ISSUE TITLE
The performance on P.Sup23 Dataset is not as expected

### ISSUE THREAD

**Issue by CosineG** [google/visqol#61]
Hi, I tested ViSQOL (both audio mode and speech mode) on ITU P.Sup23 Dataset, and made 2 scatters which contains the results of ViSQOL and PESQ. but the performance of ViSQOL  is not as expected.
![audio_mode](https://user-images.githubusercontent.com/33339051/145350773-3815c3dd-a515-485d-83bb-4eb83ce40b78.png)
![speech_mode](https://user-images.githubusercontent.com/33339051/145350769-f70933dc-ca26-41b1-9a21-fc48b11c5837.png)
As you can see the correlation between PESQ results and subjective MOS is higher. So what did I do wrong or there are something extra I need to do? Or do you have some other dataset for test? There seem to be very few public datasets with MOS.
Thanks.

**Comment by mchinen** [comment]
Hi,
This is a known issue with the current version.  The reason for this is that ViSQOL was fit to certain datasets including P Supp. 23 and the 1-d Speech similarity (1-D NSIM) is not expressive enough to represent them all.  So scores for any particular dataset are compressed, as you can see by the orange dots that represent this dataset in Figure 5a of this [paper here](https://asa.scitation.org/doi/pdf/10.1121/10.0005130).
![image](https://user-images.githubusercontent.com/327400/145638119-4667c1e8-f44b-408e-bfe6-edbbb1e1139e.png)

  The SVR model was trained only on music and does not perform well on speech either.  We have developed a new lattice model that performs well (Figure 6) but it is not in the master branch yet.  Using the current model will have these problems.  
![image](https://user-images.githubusercontent.com/327400/145638097-74c0a107-dbe3-42f9-bb0a-d90008e5d00d.png)

To a small extent the improvements could be slightly improved by rescaling the estimated scores to the dataset as described in [ITU-T Rec. P. 1401](https://www.itu.int/rec/T-REC-P.1401-202001-I/en).  

For using the lattice model, I am trying to sort out the considerable python and tensorflow requirements for cross platform usage before pushing it (due to the lattice being implemented in tensorflow), but if you would like, there is a [branch](https://github.com/mchinen/visqol/tree/visqol320) where you could test it out on linux.  However please be aware that this is likely to change significantly.

**Comment by mchinen** [comment]
A version of the new model has been merged in #66.  Please re-open if you see continued strange behavior.
